// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminTable: typeof import('./src/components/AdminTable.vue')['default']
    AppLayout: typeof import('./src/layouts/AppLayout.vue')['default']
    AuthLayout: typeof import('./src/layouts/AuthLayout.vue')['default']
    CategoriesView: typeof import('./src/views/CategoriesView.vue')['default']
    CreateDialog: typeof import('./src/views/categories/CreateDialog.vue')['default']
    DashboardView: typeof import('./src/views/DashboardView.vue')['default']
    DeleteDialog: typeof import('./src/components/DeleteDialog.vue')['default']
    EditDialog: typeof import('./src/views/categories/EditDialog.vue')['default']
    ErrorMsg: typeof import('./src/components/ErrorMsg.vue')['default']
    FilterForm: typeof import('./src/views/categories/FilterForm.vue')['default']
    IndexView: typeof import('./src/views/categories/IndexView.vue')['default']
    LoginView: typeof import('./src/views/auth/LoginView.vue')['default']
    LogoutView: typeof import('./src/components/LogoutView.vue')['default']
    PostsView: typeof import('./src/views/PostsView.vue')['default']
    RegisterView: typeof import('./src/views/auth/RegisterView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
