// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AppLayout: typeof import("./src/layouts/AppLayout.vue")["default"];
    AppLogo: typeof import("./src/components/base/AppLogo.vue")["default"];
    AuthLayout: typeof import("./src/layouts/AuthLayout.vue")["default"];
    CategoriesView: typeof import("./src/views/CategoriesView.vue")["default"];
    CreateDialog: typeof import("./src/views/categories/CreateDialog.vue")["default"];
    DashboardView: typeof import("./src/views/DashboardView.vue")["default"];
    DropdownLink: typeof import("./src/components/base/DropdownLink.vue")["default"];
    EditDialog: typeof import("./src/views/categories/EditDialog.vue")["default"];
    FilterForm: typeof import("./src/views/categories/FilterForm.vue")["default"];
    IconCommunity: typeof import("./src/components/icons/IconCommunity.vue")["default"];
    IconDocumentation: typeof import("./src/components/icons/IconDocumentation.vue")["default"];
    IconEcosystem: typeof import("./src/components/icons/IconEcosystem.vue")["default"];
    IconSupport: typeof import("./src/components/icons/IconSupport.vue")["default"];
    IconTooling: typeof import("./src/components/icons/IconTooling.vue")["default"];
    IndexView: typeof import("./src/views/categories/IndexView.vue")["default"];
    PostsView: typeof import("./src/views/PostsView.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    UploadInput: typeof import("./src/components/base/inputs/UploadInput.vue")["default"];
  }
}

export {};
